# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s


#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arjun_w/Downloads/CrosswordGenerator-05

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arjun_w/Downloads/CrosswordGenerator-05

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arjun_w/Downloads/CrosswordGenerator-05/CMakeFiles /home/arjun_w/Downloads/CrosswordGenerator-05//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arjun_w/Downloads/CrosswordGenerator-05/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Crossword_Generator

# Build rule for target.
Crossword_Generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Crossword_Generator
.PHONY : Crossword_Generator

# fast build rule for target.
Crossword_Generator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/build
.PHONY : Crossword_Generator/fast

src/grid.o: src/grid.cpp.o
.PHONY : src/grid.o

# target to build an object file
src/grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/grid.cpp.o
.PHONY : src/grid.cpp.o

src/grid.i: src/grid.cpp.i
.PHONY : src/grid.i

# target to preprocess a source file
src/grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/grid.cpp.i
.PHONY : src/grid.cpp.i

src/grid.s: src/grid.cpp.s
.PHONY : src/grid.s

# target to generate assembly for a file
src/grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/grid.cpp.s
.PHONY : src/grid.cpp.s

src/library.o: src/library.cpp.o
.PHONY : src/library.o

# target to build an object file
src/library.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/library.cpp.o
.PHONY : src/library.cpp.o

src/library.i: src/library.cpp.i
.PHONY : src/library.i

# target to preprocess a source file
src/library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/library.cpp.i
.PHONY : src/library.cpp.i

src/library.s: src/library.cpp.s
.PHONY : src/library.s

# target to generate assembly for a file
src/library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/library.cpp.s
.PHONY : src/library.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/point.o: src/point.cpp.o
.PHONY : src/point.o

# target to build an object file
src/point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/point.cpp.o
.PHONY : src/point.cpp.o

src/point.i: src/point.cpp.i
.PHONY : src/point.i

# target to preprocess a source file
src/point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/point.cpp.i
.PHONY : src/point.cpp.i

src/point.s: src/point.cpp.s
.PHONY : src/point.s

# target to generate assembly for a file
src/point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/point.cpp.s
.PHONY : src/point.cpp.s

src/slot.o: src/slot.cpp.o
.PHONY : src/slot.o

# target to build an object file
src/slot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/slot.cpp.o
.PHONY : src/slot.cpp.o

src/slot.i: src/slot.cpp.i
.PHONY : src/slot.i

# target to preprocess a source file
src/slot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/slot.cpp.i
.PHONY : src/slot.cpp.i

src/slot.s: src/slot.cpp.s
.PHONY : src/slot.s

# target to generate assembly for a file
src/slot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/slot.cpp.s
.PHONY : src/slot.cpp.s

src/solver.o: src/solver.cpp.o
.PHONY : src/solver.o

# target to build an object file
src/solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/solver.cpp.o
.PHONY : src/solver.cpp.o

src/solver.i: src/solver.cpp.i
.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/solver.cpp.i
.PHONY : src/solver.cpp.i

src/solver.s: src/solver.cpp.s
.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/solver.cpp.s
.PHONY : src/solver.cpp.s

src/span.o: src/span.cpp.o
.PHONY : src/span.o

# target to build an object file
src/span.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/span.cpp.o
.PHONY : src/span.cpp.o

src/span.i: src/span.cpp.i
.PHONY : src/span.i

# target to preprocess a source file
src/span.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/span.cpp.i
.PHONY : src/span.cpp.i

src/span.s: src/span.cpp.s
.PHONY : src/span.s

# target to generate assembly for a file
src/span.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/span.cpp.s
.PHONY : src/span.cpp.s

src/utilities.o: src/utilities.cpp.o
.PHONY : src/utilities.o

# target to build an object file
src/utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/utilities.cpp.o
.PHONY : src/utilities.cpp.o

src/utilities.i: src/utilities.cpp.i
.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/utilities.cpp.i
.PHONY : src/utilities.cpp.i

src/utilities.s: src/utilities.cpp.s
.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Crossword_Generator.dir/build.make CMakeFiles/Crossword_Generator.dir/src/utilities.cpp.s
.PHONY : src/utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Crossword_Generator"
	@echo "... src/grid.o"
	@echo "... src/grid.i"
	@echo "... src/grid.s"
	@echo "... src/library.o"
	@echo "... src/library.i"
	@echo "... src/library.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/point.o"
	@echo "... src/point.i"
	@echo "... src/point.s"
	@echo "... src/slot.o"
	@echo "... src/slot.i"
	@echo "... src/slot.s"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
	@echo "... src/span.o"
	@echo "... src/span.i"
	@echo "... src/span.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

